### ISSUE TITLE
ModuleNotFoundError: No module named 'flash_attn.flash_attention'

### ISSUE THREAD

**Issue by lineshen199466** [TencentARC-QQ/QA-CLIP#1]
[root@pytorch-339829066-master-0 QA-CLIP-main]# python3
Python 3.11.4 (main, Nov  1 2023, 16:06:27) [GCC 8.5.0 20210514 (TencentOS 8.5.0-18)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import clip as clip
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/dockerdata/adams_workspace/QA-CLIP-main/clip/__init__.py", line 4, in <module>
    from .model import convert_state_dict
  File "/dockerdata/adams_workspace/QA-CLIP-main/clip/model.py", line 16, in <module>
    FlashMHA = importlib.import_module('flash_attn.flash_attention').FlashMHA
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'flash_attn.flash_attention'

**Comment by xiaotaozi121096** [comment]
Hello, I'm also experiencing this issue. Has it been resolved yet?
